FROM ruby:2.4.5
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  libgmp3-dev \
  postgresql-client-9.6
RUN mkdir /myapp
WORKDIR /myapp
EXPOSE 3000
COPY . /myapp
RUN bundle install --without development test
ENV RAILS_ENV=production
ENV RACK_ENV=production
RUN bundle exec rake assets:precompile
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
